name: app_flutter_riverpod
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^0.13.6
  
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0


flutter:

  uses-material-design: true

